# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True)),
                ('id_name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
