# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='id_name',
            field=models.TextField(unique=True),
        ),
    ]
