# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170315_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True)),
                ('tarball', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cam',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='cam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cam'),
        ),
    ]
